apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: innerpeace
  name: doctor-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doctor
      component: web
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: doctor
        component: web
    spec:
      containers:
      - name: doctor-web
        image: asia.gcr.io/image-repository-235607/doctor-web:1.0.14
        ports:
        - containerPort: 3000
          protocol: TCP
        resources:
          requests:
            cpu: 0.5
          limits:
            cpu: 1
        volumeMounts:
        - name: env-vol
          mountPath: /tmp/js/env/
        args: ["/usr/src/app/scripts/release/serve.sh"]
      volumes:
        - name: env-vol
          configMap:
            name: env-doctor-web
---
kind: Service
apiVersion: v1
metadata:
  namespace: innerpeace
  name: doctor-web-service
spec:
  selector:
    app: doctor
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
