apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: innerpeace
  name: doctor-web-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doctor-dev
      component: web
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: doctor-dev
        component: web
    spec:
      containers:
      - name: doctor-web-dev
        image: asia.gcr.io/image-repository-235607/doctor-web:0.1.29-4-8
        ports:
        - containerPort: 3000
          protocol: TCP
        resources:
          requests:
            cpu: 0.5
          limits:
            cpu: 1
        volumeMounts:
        - name: env-vol
          mountPath: /tmp/js/env/
        args: ["/usr/src/app/scripts/release/serve.sh"]
      volumes:
        - name: env-vol
          configMap:
            name: env-doctor-web-dev
---
kind: Service
apiVersion: v1
metadata:
  namespace: innerpeace
  name: doctor-web-dev-service
spec:
  selector:
    app: doctor-dev
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
